name: release

on:
  workflow_dispatch:
  push:

jobs:
  release:
    runs-on: ubuntu-22.04
    permissions:
      contents: write       # for creating the gh release
      issues: write         # for commenting on related issues
      pull-requests: write  # for commenting on related pull-requests
      
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0 # semantic release needs all the history
      - uses: actions/setup-node@v2
      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npx semantic-release@19